server:
  port: 8085

spring:
  sql:
    init:
      mode: always
  datasource:
    url: "jdbc:postgresql://localhost:5432/trackdynamics"
    driverClassName: 'org.postgresql.Driver'
    username: 'alquimistas'
    password: '123456'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

logging:
  level:
    root: INFO